site_name: 名笔记
site_description: 全栈、DevOPS、Python、Go、Docker、Kubernetes、Linux、云原生、前端、后端、运维...
site_url: https://www.numachen.github.io

theme:
  name: material
  features:
    - navigation.indexes

hooks:
  - hooks/hooks.py
  - hooks/socialmedia.py

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Holidays
        - News
      authors_profiles: true
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
#      post_slugify: !!python/object/apply:ext.slugs.slugify
#        kwds:
#          short: true
#  - meta
  - tags
#  - rss:
#      match_path: "blog/posts/.*"
#      date_from_meta:
#        as_creation: date.created
#        as_update: date.updated

extra:
  social:
    - icon: fontawesome/brands/mastodon
      name: squidfunk on Mastodon
      link: https://fosstodon.org/@squidfunk

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - 首页: index.md
  - 前端:
      - frontend/index.md
      - frontend/tags.md
  - 后端:
      - backend/index.md
      - backend/tags.md
  - 云原生:
      - blog/index.md
      - blog/tags.md